### ISSUE TITLE
Fix memory leak issue

### ISSUE THREAD

**Issue by hlechner** [hlechner/wwidd#10]
example:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.EventEmitter.addListener (events.js:178:15)
    at process.on.process.addListener (node.js:599:26)
    at envelope (/home/hlechner/wwidd_testes/wwidd/server/src/ajax/envelope.js:43:10)
    at Object.run (/home/hlechner/wwidd_testes/wwidd/server/src/ajax/system.js:25:3)
    at Server.<anonymous> (/home/hlechner/wwidd_testes/wwidd/server/src/server.js:70:10)
    at Server.EventEmitter.emit (events.js:96:17)
    at HTTPParser.parser.onIncoming (http.js:1824:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socket.ondata (http.js:1721:22)
    at TCP.onread (net.js:403:27)
```

**Comment by hlechner** [comment]
Example 1:

Steps to reproduce:
- Select a video
- Click on **Actions** > **Refresh Thumbnails**

it will return the following line:
`TOOL - executing: gzip`

Until it receive a memory leak warning:

```
TOOL - executing: gzip 
TOOL - executing: gzip 
TOOL - executing: gzip 
TOOL - executing: gzip 
TOOL - executing: gzip 
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.EventEmitter.addListener (events.js:178:15)
    at process.on.process.addListener (node.js:599:26)
    at envelope (/home/hlechner/wwidd_testes/wwidd/server/src/ajax/envelope.js:43:10)
    at Object.run (/home/hlechner/wwidd_testes/wwidd/server/src/ajax/system.js:25:3)
    at Server.<anonymous> (/home/hlechner/wwidd_testes/wwidd/server/src/server.js:70:10)
    at Server.EventEmitter.emit (events.js:96:17)
    at HTTPParser.parser.onIncoming (http.js:1824:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socket.ondata (http.js:1721:22)
    at TCP.onread (net.js:403:27)

```
